project:
  type: website
  output-dir: "."

website:
  title: "Samuel Lee's Data Analytics Website"
  navbar:
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
      - text: "Project"
        menu:
          - project.qmd
          

page-footer: 
    center: "Powered with GitHub and Quarto<br>© Samuel Lee, 2023"

format:
  html:
    theme: darkly
    mainfont: system-ui; 
    highlight-style: kate
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
    
    
    
